### ISSUE TITLE
[Beta] Download animation is not working for episodes

### ISSUE THREAD

**Issue by rachitmishra** [razeware/emitron-Android#226]

**Comment by filbabic** [comment]
Hey @rachitmishra could you elaborate a bit more in which way this animation doesn't work? And maybe give me repro steps, if possible?

Thanks! :]

**Comment by alienvelour** [comment]
@filbabic Appears that this is either fixed, or the original issue may have been erroneous, since it may have just been seen when the download is fast. Closing this issue for now based on Luke's comment.
