### ISSUE TITLE
Global: Reduce space at top of all screens

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-Android#314]
There's a significant space at the top of every screen. 

Is there a reason that's there?

### Expected behavior

Screen content sits flush/with reasonable padding to the top of the screen

### Actual behavior

![Screenshot 2020-12-18 at 11 53 24](https://user-images.githubusercontent.com/5320361/102606815-a7d1b300-4127-11eb-90ed-8893a24bae33.png)

### Environment

* Android Version: 9
* raywenderlich.com App Version: 1.1.0
* Device: Galaxy S8

**Comment by KelvnPere** [comment]
@sammyd If this is still an issue. I will like to work on this.

**Comment by sammyd** [comment]
@KelvnPere go for it!

**Comment by KelvnPere** [comment]
> @KelvnPere go for it!

Thanks!

**Comment by KelvnPere** [comment]
Based on my evaluation and test it appears this is an issue that doesn't affect the latest app Kodeco version 2.0.0, the report was made using a much earlier version. 

Tested on 
1) Pixel 3A (API 31) Android version 12
2) Samsung Galaxy A53 version 13

@sammyd this issue can be closed. Thanks.

**Comment by sammyd** [comment]
Thanks for testing!
