### ISSUE TITLE
Settings: Move to its own tab

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-Android#315]
Move settings to it's own tab in the navigation and remove it from the 'My Tutorials'. This will allow us to eventually add controls to My Tutorials to filter/remove all etc.

### Expected behavior

Settings has it's own tab

Figma: https://www.figma.com/file/Sh3IyUBB0El4WiPamLNv4g/Emitron-Android?node-id=0%3A1243

![Screenshot 2020-12-18 at 12 03 52](https://user-images.githubusercontent.com/5320361/102607762-23802f80-4129-11eb-96b4-a019c5f3e0a8.png)

### Actual behavior

Settings lives under My Tutorials

### Environment

* Android Version: 9
* raywenderlich.com App Version: 1.1.0
* Device: Galaxy S8

**Comment by filbabic** [comment]
![Screenshot_1615978421](https://user-images.githubusercontent.com/17215808/111457961-2636f480-8719-11eb-962f-5faf3ab4e624.png)
![Screenshot_1615978423](https://user-images.githubusercontent.com/17215808/111457962-26cf8b00-8719-11eb-9662-0abd0556cc5e.png)
![Screenshot_1615978427](https://user-images.githubusercontent.com/17215808/111457965-27682180-8719-11eb-9fb4-e73e84ffea71.png)

@luke-freeman  How does this look? :]

**Comment by filbabic** [comment]
You'll probably notice that there are no titles for the icons unless the item is focused.

This is the default Android behavior and sadly it cannot be changed unless we use a third party hacked copy of the library and then add it.

But this would require of us to completely re-do the navigation we have currently, which is quite painful to do.

**Comment by luke-freeman** [comment]
@filbabic Lol that's crazy about the titles. It looks great!

**Comment by filbabic** [comment]
@luke-freeman Oh I actually did a bit more digging in the meantime and it seems there's been a change where that is now actually possible! :]

I'll add the labels then.

If the rest looks fine, I'll merge this once Rachit reviews the code!
