### ISSUE TITLE
Course Homepage: Locked content remove paragraph

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-Android#316]
On locked content remove the paragraph. The title and call to action are sufficient and the paragrpah just looks messy and cramped. 

### Steps to reproduce

Sign in as a beginner subscriber

### Expected behavior

Locked content has title 'Pro Course' and green call to action

### Actual behavior

Paragraph text makes this section look cluttered and messy

![Screenshot_20201218-120626_raywenderlich](https://user-images.githubusercontent.com/5320361/102608239-e0728c00-4129-11eb-86a9-8baf90242c04.jpg)

### Environment

* Android Version: 9
* raywenderlich.com App Version: 1.1.0
* Device: Samsung S8

**Comment by filbabic** [comment]
![header-1](https://user-images.githubusercontent.com/17215808/111450518-c2a8c900-8710-11eb-9962-7bd482e9c733.png)
![header-2](https://user-images.githubusercontent.com/17215808/111450521-c3d9f600-8710-11eb-987f-dbb16b9a5bb9.png)

Hey @luke-freeman!

Which one of these two options do you prefer? We can have the order of the two items display in other ways too, if needed.

Thanks!

**Comment by filbabic** [comment]
@luke-freeman Pinging here just to make sure you've seen this!
