### ISSUE TITLE
System navigation bar overlaps with buttons

### ISSUE THREAD

**Issue by OsvaldoAlc** [razeware/emitron-Android#335]
System navigation bar overlaps with buttons

### Steps to reproduce
The bug is found on the login and filter videos screen

### Expected behavior
Buttons should appear above the system navigation bar.

### Actual behavior
"Sign in", "Clear All", "Apply" buttons appear behind the system navigation bar.

### Environment
* Android Version: 10
* raywenderlich.com App Version: 1.2.0-debug
* Device: samsung A70
![Screenshot_20210804-164112_raywenderlich](https://user-images.githubusercontent.com/22378168/128259338-4e189cd5-3bdb-4c17-a9b7-9e88da120261.jpg)
![Screenshot_20210804-164352_raywenderlich](https://user-images.githubusercontent.com/22378168/128259342-d7cda5bf-4687-43d7-84e8-2a19fcdd48f6.jpg)

**Comment by KelvnPere** [comment]
@OsvaldoAlc Can you confirm if this is still an issue?

**Comment by OsvaldoAlc** [comment]
issue is no longer present
