### ISSUE TITLE
Update Room to Support M1 Macbooks

### ISSUE THREAD

**Issue by jumaallan** [razeware/emitron-Android#340]
The project does not compile on an M1 Mac, since the Room version used is old and doesn't have native sqlite library needed

### Steps to reproduce

* Clone the repo on an M1 Mac
* Run the app on an emulator or a physical device

### Expected behavior

I expect the app to be installed on my device or the emulator

### Actual behavior

Android Studio throws this error

```yaml
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
```

### Environment

* Android Version: Any version
* raywenderlich.com App Version: Latest development branch
* Device: Any device

**Comment by wangerekaharun** [comment]
This issue is already fixed. Going ahead to close this.
