### ISSUE TITLE
Unable to access content

### ISSUE THREAD

**Issue by sammyd** [razeware/emitron-Android#352]
There are new content permissions that prevent access to content for new subscribers.

These tags are "stream-team-videos" and "stream-personal-videos". Users and content have them. In iOS, the following change was made to support them, which is a bit hacky, but it works:

https://github.com/razeware/emitron-iOS/commit/094b3f390415bd6dae3d68c8937426c26a9ad74c

There should be something equivalent in Android to address the same issue.

**Comment by KelvnPere** [comment]
@sammyd You can assign this task to me. Thanks

**Comment by KelvnPere** [comment]
Link to PR @sammyd 

https://github.com/razeware/emitron-Android/pull/353
