### ISSUE TITLE
Downloaded episodes don't display on downloads screen

### ISSUE THREAD

**Issue by tgblank** [razeware/emitron-Android#54]
If I download a single episode from a video course, it does not show up in the download list.

https://github.com/raywenderlich/emitron-Android/tree/downloads-offline

**Comment by alienvelour** [comment]
@tgblank Are you still seeing this? I tested this with a few courses and was not able to repro.

**Comment by tgblank** [comment]
I haven’t seen this happen in the latest release.

**Comment by alienvelour** [comment]
Closing as appears fixed in current release.
